services:
  - type: web
    name: assassins-game
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:create_app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: assassins-db
          property: connectionString
databases:
  - name: assassins-db
    plan: free
