"""Remove test_column

Revision ID: 01055fd628c2
Revises: 0035139fbf8b
Create Date: 2025-08-01 23:33:06.692913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01055fd628c2'
down_revision = '0035139fbf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
