"""Remove test_flag from Player

Revision ID: 4ca39903aedf
Revises: f0c6db6818fd
Create Date: 2025-08-06 00:09:48.195438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca39903aedf'
down_revision = 'f0c6db6818fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('test_flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_flag', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
